name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then make install; fi
      - name: Install dependencies for development
        run: |
          if [ -f requirements.dev.txt ]; then make install-dev; fi

      - name: Lint
        run: |
          make lint
      - name: Format
        run: |
          make format
